spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.0.103:1521:orcl
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.driver.OracleDriver
    continue-on-error: true
    hikari:
      connection-timeout: 10000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    com.xkcoding: debug
    com.xkcoding.orm.mybatis.MapperAndPage.mapper: trace
mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.group4.backend.entity
